// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iCiS.Models;

namespace iCiS.Migrations
{
    [DbContext(typeof(iCiSContext))]
    [Migration("20180722034456_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("iCiS.Models.Servidor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Fecha_captura");

                    b.Property<string>("Nombre");

                    b.Property<string>("Sistema_operativo");

                    b.HasKey("ID");

                    b.ToTable("Servidor");
                });
#pragma warning restore 612, 618
        }
    }
}
